services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: harmony_frontend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - PORT=3000
      - HOSTNAME=0.0.0.0
